[theme]
primaryColor = "#4B8BF5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableStaticServing = true

[global]
showWarningOnDirectExecution = false

[deprecation]
showPyplotGlobalUse = false